[package]
name = "imagepipe"
version = "0.4.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]
description = "An image processing pipeline"
documentation = "https://docs.rs/imagepipe/"
#homepage = "..."
repository = "https://github.com/pedrocr/imagepipe"
license = "LGPL-3.0-only"
categories = ["multimedia::images"]
edition = "2018"

[dependencies]
lazy_static = "1"
multicache = "0.6.1"
rayon = "1"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
bincode = "1"
blake3 = "0.3"
log = "0.4"
num-traits = "0.2"

[dependencies.image]
version = "0.23"
git = "https://github.com/pedrocr/image"
branch = "dynimage_width_height"

[dependencies.rawloader]
version = "0.37"
path = "../rawloader"

[profile.dev]
opt-level = 3

[[bin]]
name = "converter"
doc = false
